[#27] Implemented sample usage for the lib.
inbangsa/Logger pull request #28
Opened 2020-06-11 09:37 UTC by tamerharsh

2020-06-12 04:21 UTC, sachinsnale approved these changes
Just do that indentation changes

2020-06-12 04:21 UTC, sachinsnale commented on sample/sample.cpp
> +logger::Logger logging_obj ;
Please look after proper indentation,
please check for whole file

2020-06-12 11:26 UTC, sachinsnale requested changes

2020-06-12 11:26 UTC, sachinsnale commented on sample/sample.cpp
> +    return number_1 / number_2;
Either have this
```
if (number_2 == 0)
    throw std::exception("Divisor cannot be zero.");
else
    return number_1 / number_2;
```
Or this
```
if (number_2 == 0){
    throw std::exception("Divisor cannot be zero.");
}
else{
    return number_1 / number_2;
}
```

2020-06-15 04:34 UTC, sachinsnale approved these changes

2020-06-15 04:36 UTC, tamerharsh commented
Merging with approval.

2020-06-15 04:45 UTC, merged